# name=input("enter your name")
# age=int(input("enter your age"))
# age1=22
# print(type(name))
# print(type(age))
# print("your name is ",name)
# print("your age is ",age)
# print(f"your age is {age1}")
# print(f"your name is {name}")
# firstname="dinesh"
# lastname="rr"
# finalname=firstname+lastname
# print(finalname)
# fullname=firstname+" "+lastname
# print(fullname)
# print("your first name is {}last name is {} your full name is{}".format(firstname,lastname,fullname))
# print("your last name is {} your fullname is {} your firstname is {}".format(lastname,fullname,firstname))
# print(firstname[-6])
# print(firstname[0:6])
# print(firstname[:])
# print(firstname[-6:])
# print(firstname[0:6:2])
a="dinesh"
b="rr"
print(a.capitalize())
print(b.capitalize())
print(b.count("r",0,0))
print(a.count("dinesh",0,1))
print(a.lower())
print(a.islower())
print(a.upper())
print(a.isupper())
print(a.swapcase())
print(a.title())
print(a.istitle())
print(a.startswith("e"))
print(a.endswith("h"))
print(a.isalnum())
print(a.find("d"))
print(a.index("e"))
print(b.replace("rr","RR"))
print(a.strip("dines"))
print(a.ljust(8,'R'))
print(a.rjust(8,'d'))
print(a.center(8,'d'))